# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/pnpm-workspace.json

minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@revenuecat/*'

saveExact: true
